---
services:
	inventory:
		git_url: git@github.com:xtqmc/coachbase-optinmonster.git
		git_branch: master
		command: npm start
		build_root: .
		ports:
		- container: 8080
		- http: 80
		- https: 443
		NODE_ENV: production
